
# TODO: Read ENV LDAP_ADMIN_PASSWORD, LDAP_UNSAFE_SELFWRITE_ACL, LDAP_PURGE_DATABASE, LDAP_DOMAIN, LDAP_PPOLICY_SCHEMA_NEEDS_UPDATE, LDAP_INVALID_CONFIG, LDAP_MOVE_OLD_DATABASE, LDAP_BACK_END, LDAP_ORGANISATION_NAME, LDAP_BACKUP_DIR, LDAP_NO_CONFIGURATION, LDAP_DUMP_DATABASE, 

version: "3.2"
services:
        ldap_server:
                build: ./openldap-ubuntu
                image: drussell1974/openldap:ldap-v2020.06.18.065009
                environment:
                        - LDAP_ADMIN_USER=${LDAP_ADMIN_USER:-cn=admin}
                        - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD:-admin}
                        - LDAP_BACKUP_DIR=${LDAP_BACKUP_DIR:-examplenet}
                        - LDAP_BASE_DN=${LDAP_BASE_DN:-dc=example,dc=net}
                        - LDAP_DOMAIN=${LDAP_DOMAIN:-example.net}
                        - LDAP_INIT=${LDAP_INIT:-false}
                        - LDAP_INIT_BOOTSTRAP=${LDAP_INIT_BOOTSTRAP:-false}
                        - LDAP_INIT_LDIF_PATH=${LDAP_INIT_LDIF_PATH:-init/ldif/init.ldif}
                        - LDAP_NFS_SERVER_IPADDR=${LDAP_NFS_SERVER_IPADDR}
                        - LDAP_ORGANIZATION_NAME=${LDAP_ORGANIZATION_NAME:-Example.Net}
                ports:
                        - 389:389
                        - 636:636
        nfs_server:
                build: ./nfs-server
                image: drussell1974/openldap:nfs-v2020.06.18.065009
                external_links:
                        - ldap_server
                environment:
                        - NFS_IPADDR_ALLOWED=${NFS_IPADDR_ALLOWED}
                        - NFS_PUBLIC_CONT=${NFS_PUBLIC_CONT}
                        - NFS_HOME_CONT=${NFS_HOME_CONT}
                volumes:
                        - /mnt/nfs_share/Public:${NFS_PUBLIC_CONT}
                        - /mnt/nfs_share/home:${NFS_HOME_CONT}
                ports:
                        - 2049:2049


